#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 19 21:12:58 2018

@author: mbenkhal
"""

from pandas import DataFrame, read_csv
import matplotlib.pyplot as plt
import pandas as pd
Location_one=r'/Users/mbenkhal/Documents/Avivo/MergedData.xlsx'
Location_two=r'/Users/mbenkhal/Documents/Avivo/admission_discharge_demographic-2.xlsx'
data_one =  pd.read_excel(Location_one)
data_two =  pd.read_excel(Location_two)
data_one.head(5)
data_two.head(5)
data_discharge = data_two[data_two['Form.Flag'] == 'discharge']
#data_one["end_service_data"]=pd.to_datetime(data_one["end_service_data"])
#data_one["Reason.discharge"]='not found'
#data_discharge["Form.Date"] = pd.to_datetime(data_discharge["Form.Date"])


for index_2, row_2 in data_one.iterrows():
    for index_1, row_1 in data_discharge.iterrows():
        
        if(row_1[3]== row_2[0] and row_1[1] == row_2[1]):
        
            print('true')
            data_one['Reason.discharge'][index_2] = data_discharge["Reason.for.Discharge"][index_1]
            
            
            
data_one.to_excel(r'/Users/mbenkhal/Documents/Avivo/MergedData.xlsx')